### ISSUE TITLE
Check for bug in generate_polarization(xray_angle,scattering_angle)

### ISSUE THREAD

**Issue by mpmdean** [gfabbris/multiplety#6]
generate_polarization(xray_angle, scattering_angle)

with xray_angle=90 and scattering_angle=90

should return
[1/sqrt(2), 0 1j/sqrt(2)]
not
[1/sqrt(2), 0 1/sqrt(2)]

**Comment by gfabbris** [comment]
I think this is right:

R (right pol.)  = (x (x pol.) - j*y (y pol.))/sqrt(2)
L (left pol.) = (x + j*y)/sqrt(2)

Then:
x = (R+L)/sqrt(2)
y = j*(R+L)/sqrt(2)

But the definition of y pol. in the example_rixs_dichroism notebook is wrong, I just corrected it.

**Comment by mpmdean** [comment]
I agree with the first two lines, but disagree with the second

Can you look at
https://github.com/mpmdean/multiplety/blob/master/notes/notes.pdf

@shenmidelin -- please confirm

**Comment by shenmidelin** [comment]
I have checked the source codes in generate_polarization(xray_angle, scattering_angle), the code is right. 
R = (x - 1j*y)/sqrt(2)
L = (x + 1j*y)/sqrt(2)
for H polarization, y=0, so R=L=x/sqrt(2.0)

**Comment by gfabbris** [comment]
Sorry, my reply actually has a mistake -  y = j(R-L)/sqrt(2), I'm fixing the notebook again...

@mpmdean -- I think the formulas 1 and 2 in the notes are wrong. The definitions are:

*R = (x - jy)/sqrt(2)
L = (x + jy)/sqrt(2)*

Then if you sum these two equations:
*R+L = 2x/sqrt(2) -> x = (R+L)/sqrt(2)*

and if you subtract them:
*R-L = -2jy/sqrt(2) -> y = j(R-L)/sqrt(2)*
